const GET_EVENT_TYPES_SUCCESS = 'GET_EVENT_TYPES_SUCCESS';
const GET_EVENT_TYPES_FAILURE = 'GET_EVENT_TYPES_FAILURE';
const GET_EVENT_TYPES_REQUEST = 'GET_EVENT_TYPES_REQUEST';
const CREATE_EVENT_TYPES_SUCCESS = 'CREATE_EVENT_TYPES_SUCCESS';
const CREATE_EVENT_TYPES_FAILURE = 'CREATE_EVENT_TYPES_FAILURE';
const CREATE_EVENT_TYPES_REQUEST = 'CREATE_EVENT_TYPES_REQUEST';
const UPDATE_EVENT_TYPES_SUCCESS = 'UPDATE_EVENT_TYPES_SUCCESS';
const UPDATE_EVENT_TYPES_FAILURE = 'UPDATE_EVENT_TYPES_FAILURE';
const UPDATE_EVENT_TYPES_REQUEST = 'UPDATE_EVENT_TYPES_REQUEST';
const DELETE_EVENT_TYPES_SUCCESS = 'DELETE_EVENT_TYPES_SUCCESS';
const DELETE_EVENT_TYPES_FAILURE = 'DELETE_EVENT_TYPES_FAILURE';
const DELETE_EVENT_TYPES_REQUEST = 'DELETE_EVENT_TYPES_REQUEST';

export {
    GET_EVENT_TYPES_SUCCESS,
    GET_EVENT_TYPES_FAILURE,
    GET_EVENT_TYPES_REQUEST,
    CREATE_EVENT_TYPES_SUCCESS,
    CREATE_EVENT_TYPES_FAILURE,
    CREATE_EVENT_TYPES_REQUEST,
    UPDATE_EVENT_TYPES_SUCCESS,
    UPDATE_EVENT_TYPES_FAILURE,
    UPDATE_EVENT_TYPES_REQUEST,
    DELETE_EVENT_TYPES_SUCCESS,
    DELETE_EVENT_TYPES_FAILURE,
    DELETE_EVENT_TYPES_REQUEST,
}

export type CreateEventTypeTyped = {
    name: string;
}

export type EventTypesTypes = {
    id: number;
    name: string;
}

export type EventTypesState = {
    eventTypes: EventTypesTypes[];
    isLoading: boolean;
    error: any;
}
