const GET_GALLERY_SUCCESS = 'GET_GALLERY_SUCCESS';
const GET_GALLERY_FAILURE = 'GET_GALLERY_FAILURE';
const GET_GALLERY_REQUEST = 'GET_GALLERY_REQUEST';
const GET_GALLERY_BY_ID_SUCCESS = 'GET_GALLERY_BY_ID_SUCCESS';
const GET_GALLERY_BY_ID_FAILURE = 'GET_GALLERY_BY_ID_FAILURE';
const GET_GALLERY_BY_ID_REQUEST = 'GET_GALLERY_BY_ID_REQUEST';
const DELETE_GALLERY_SUCCESS = 'DELETE_GALLERY_SUCCESS';
const DELETE_GALLERY_FAILURE = 'DELETE_GALLERY_FAILURE';
const DELETE_GALLERY_REQUEST = 'DELETE_GALLERY_REQUEST';
const CREATE_GALLERY_SUCCESS = 'CREATE_GALLERY_SUCCESS';
const CREATE_GALLERY_FAILURE = 'CREATE_GALLERY_FAILURE';
const CREATE_GALLERY_REQUEST = 'CREATE_GALLERY_REQUEST';
const UPDATE_GALLERY_SUCCESS = 'UPDATE_GALLERY_SUCCESS';
const UPDATE_GALLERY_FAILURE = 'UPDATE_GALLERY_FAILURE';
const UPDATE_GALLERY_REQUEST = 'UPDATE_GALLERY_REQUEST';

export {
  GET_GALLERY_SUCCESS,
  GET_GALLERY_FAILURE,
  GET_GALLERY_REQUEST,
  GET_GALLERY_BY_ID_SUCCESS,
  GET_GALLERY_BY_ID_FAILURE,
  GET_GALLERY_BY_ID_REQUEST,
  DELETE_GALLERY_SUCCESS,
  DELETE_GALLERY_FAILURE,
  DELETE_GALLERY_REQUEST,
  CREATE_GALLERY_SUCCESS,
  CREATE_GALLERY_FAILURE,
  CREATE_GALLERY_REQUEST,
  UPDATE_GALLERY_SUCCESS,
  UPDATE_GALLERY_FAILURE,
  UPDATE_GALLERY_REQUEST,
}

export type CreateGalleryTyped = {
  img: string;
}

export type GalleryTyped = {
  id: number;
  img: string;
  created_at: string;
}

export type GalleryState = {
  gallery: GalleryTyped[];
  isLoading: boolean;
  error: any;
  isMore: boolean;
}

export type GalleryByIdState = {
  gallery: GalleryTyped | null;
  isLoading: boolean;
  error: any;
}
