const GET_MENU_CATEGORIES_REQUEST = 'GET_MENU_CATEGORIES_REQUEST';
const GET_MENU_CATEGORIES_SUCCESS = 'GET_MENU_CATEGORIES_SUCCESS';
const GET_MENU_CATEGORIES_FAILURE = 'GET_MENU_CATEGORIES_FAILURE';
const CREATE_MENU_CATEGORY_REQUEST = 'CREATE_MENU_CATEGORY_REQUEST';
const CREATE_MENU_CATEGORY_SUCCESS = 'CREATE_MENU_CATEGORY_SUCCESS';
const CREATE_MENU_CATEGORY_FAILURE = 'CREATE_MENU_CATEGORY_FAILURE';
const UPDATE_MENU_CATEGORY_REQUEST = 'UPDATE_MENU_CATEGORY_REQUEST';
const UPDATE_MENU_CATEGORY_SUCCESS = 'UPDATE_MENU_CATEGORY_SUCCESS';
const UPDATE_MENU_CATEGORY_FAILURE = 'UPDATE_MENU_CATEGORY_FAILURE';
const DELETE_MENU_CATEGORY_REQUEST = 'DELETE_MENU_CATEGORY_REQUEST';
const DELETE_MENU_CATEGORY_SUCCESS = 'DELETE_MENU_CATEGORY_SUCCESS';
const DELETE_MENU_CATEGORY_FAILURE = 'DELETE_MENU_CATEGORY_FAILURE';

export {
  GET_MENU_CATEGORIES_REQUEST,
  GET_MENU_CATEGORIES_SUCCESS,
  GET_MENU_CATEGORIES_FAILURE,
  CREATE_MENU_CATEGORY_REQUEST,
  CREATE_MENU_CATEGORY_SUCCESS,
  CREATE_MENU_CATEGORY_FAILURE,
  UPDATE_MENU_CATEGORY_REQUEST,
  UPDATE_MENU_CATEGORY_SUCCESS,
  UPDATE_MENU_CATEGORY_FAILURE,
  DELETE_MENU_CATEGORY_REQUEST,
  DELETE_MENU_CATEGORY_FAILURE,
  DELETE_MENU_CATEGORY_SUCCESS
}

export type CreateMenuCategoryTyped = {
  name: string;
  cornerId: number;
}

export type UpdateMenuCategoryTyped = {
  name: string;
}

export type MenuCategoryTyped = {
  id: number;
  name: string;
}

export type MenuCategoryState = {
  menuCategories: MenuCategoryTyped[];
  isLoading: boolean;
  error: any;
}
